_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
action_shape:
    value:
        - 1
batch_size:
    value: 64
buffer:
    value: ./buffers/InvertedPendulum-v5/size1000000_std0.0_prand0.0.pth
clip_ratio:
    value: 0.2
coef_ent:
    value: 0
cuda:
    value: false
description:
    value: Testing smaller networks
disc_hidden_sizes:
    value:
        - 100
        - 100
disc_lr:
    value: 0.0003
discount_factor:
    value: 0.995
env_id:
    value: InvertedPendulum-v5
epoch_disc:
    value: 10
epoch_ppo:
    value: 50
eval_interval:
    value: 10000
gae_lambda:
    value: 0.97
hidden_sizes:
    value:
        - 64
        - 64
learning_rate:
    value: 0.0003
max_episode_steps:
    value: unknown
max_grad_norm:
    value: 10
mix_buffer:
    value: 1
num_eval_episodes:
    value: 5
num_steps:
    value: 1000000
rollout_length:
    value: 2000
seed:
    value: 0
state_shape:
    value:
        - 4
xml_file:
    value: ./xml/InvertedPendulum-v5/regular.xml
