defaults:
  seed: 10
  eval_interval: 50000
  num_eval_episodes: 5

  # AIRL specific parameters
  learning_rate: 0.0003 # lr_actor and lr_critic
  disc_lr: 0.0003 # lr_disc
  hidden_sizes: [256, 256] # units_actor and units_critic
  hidden_units_r: [32] # layers for the g term in the discriminator
  hidden_units_v: [32, 32] # layers for the h term in the discriminator
  clip_ratio: 0.2
  gamma: 0.995 # discount factor
  gae_lambda: 0.97
  mix_buffer: 20
  batch_size: 128
  epoch_ppo: 25
  epoch_disc: 25
  coef_ent: 0.0
  max_grad_norm: 10.0
  cuda: true

# Environment-specific defaults
environments:
  Hopper-v5:
    xml_file: "./xml/Hopper-v5/hopper.xml"
    buffer: "./buffers/Hopper-v5/size1000000_std0.0_prand0.0_return3891.2.pth"
    num_steps: 20000000
    rollout_length: 20000
    hidden_sizes: [256, 256]
    gamma: 0.999
    gae_lambda: 0.99
    max_grad_norm: 0.7
    disc_lr: 0.00005
    learning_rate: 0.00005
    epoch_ppo: 20
    epoch_disc: 20

  InvertedPendulum-v5:
    xml_file: "./xml/InvertedPendulum-v5/invpend.xml"
    buffer: "./buffers/InvertedPendulum-v5/size1000000_std0.0_prand0.0_return1000.pth"
    num_steps: 250000
    eval_interval: 10000
    rollout_length: 2000
    hidden_sizes: [64, 64]

  Ant-v5:
    xml_file: "./xml/Ant-v5/ant.xml"
    buffer: "./buffers/Ant-v5/size1000000_std0.0_prand0.0_return5323.7.pth"
    num_steps: 20000000
    rollout_length: 20000
    hidden_sizes: [256, 256]
    gae_lambda: 0.9
    hidden_units_r: [32]
    hidden_units_v: [32, 32]
    disc_lr: 0.00005
    max_grad_norm: 0.7
    learning_rate: 0.00005
    clip_ratio: 0.7
    batch_size: 256
    epoch_ppo: 40
    epoch_disc: 40

  Pusher-v5:
    xml_file: "./xml/Pusher-v5/pusher.xml"
    buffer: "./buffers/Pusher-v5/size1000000_std0.0_prand0.0_return-31.2.pth"
    num_steps: 10000000
    rollout_length: 2048
    gae_lambda: 0.9
    max_grad_norm: 0.5
    disc_lr: 0.00005
    epoch_ppo: 30
    epoch_disc: 30
    clip_ratio: 0.4
    learning_rate: 0.0001
    max_grad_norm: 0.5
    hidden_sizes: [256, 256]
    gamma: 0.99

# Named experiments that can be used across environments
experiments:
  normal_env:
    description: "Uses default environment xml"

