# Behavioral Cloning (BC) Hyperparameters

defaults:
  seed: 0
  # BC specific parameters
  learning_rate: 0.0003
  batch_size: 64
  epochs: 10

  # Evaluation parameters
  eval_interval: 1
  num_eval_episodes: 10

  # General settings
  cuda: true # Use GPU if available

# Environment-specific defaults
environments:
  Hopper-v5:
    xml_file: "./xml/Hopper-v5/regular.xml"
    buffer: "./buffers/Hopper-v5/size1000000_std0.01_prand0.0_return2306.pth"
    epochs: 20
    policy_hidden_sizes: [64, 64]
    batch_size: 128

  HalfCheetah-v5:
    xml_file: "./xml/HalfCheetah-v5/regular.xml"
    buffer: "./buffers/HalfCheetah-v5/size1000000_std0.0_prand0.0.pth"
    epochs: 20
    policy_hidden_sizes: [256, 256]

  InvertedPendulum-v5:
    xml_file: "./xml/InvertedPendulum-v5/regular.xml"
    buffer: "./buffers/InvertedPendulum-v5/size1000000_std0.0_prand0.0_return1000.pth"
    policy_hidden_sizes: [64, 64]

  Ant-v5:
    xml_file: "./xml/Ant-v5/regular.xml"
    buffer: "./buffers/Ant-v5/size1000000_std0.01_prand0.0_return3075.9.pth"
    epochs: 30
    policy_hidden_sizes: [256, 256]

# Named experiments (Optional for BC, but can be used for variations)
# Example: Maybe testing different learning rates or network sizes
experiments:
  normal_env:
    description: "Standard BC run using environment defaults."
