# config/dagger_config.yaml
defaults:
  seed: 0
  num_steps: 10000
  num_episodes: 1000
  eval_interval: 1000
  num_eval_episodes: 5

  # DAgger specific parameters
  learning_rate: 0.0003 # lr_actor
  hidden_sizes: [256, 256]
  batch_size: 64
  rollout_length: 1000
  discount_factor: 0.99 # gamma
  beta: 0.0 # Initially use pure learner policy (0.0) vs expert (1.0)
  cuda: true

# Environment-specific defaults
environments:
  Hopper-v5:
    xml_file: "./xml/Hopper-v5/regular.xml"
    buffer: "./buffers/Hopper-v5/size1000000_std0.01_prand0.0_return3458.9.pth"
    expert: "./logs/Hopper-v5/expert/sac/seed0-20250331-1045/model/step580000"
    hidden_sizes: [64, 64]
    batch_size: 128
    num_steps: 500000
    rollout_length: 3000

  HalfCheetah-v5:
    xml_file: "./xml/HalfCheetah-v5/regular.xml"
    buffer: "./buffers/HalfCheetah-v5/size1000000_std0.01_prand0.0_return11248.4.pth"
    batch_size: 128
    num_steps: 500000
    rollout_length: 3000

  InvertedPendulum-v5:
    xml_file: "./xml/InvertedPendulum-v5/regular.xml"
    buffer: "./buffers/InvertedPendulum-v5/size1000000_std0.01_prand0.0_return1000.0.pth"
    expert: "./logs/InvertedPendulum-v5/sac/seed0-20250218-1704/model/step100000"
    hidden_sizes: [64, 64]

  Ant-v5:
    xml_file: "./xml/Ant-v5/regular.xml"
    buffer: "./buffers/Ant-v5/size1000000_std0.01_prand0.0_return3075.9.pth"
    rollout_length: 3000
    num_steps: 500000

  Pusher-v5:
    xml_file: "./xml/Pusher-v5/regular.xml"
    buffer: "./buffers/Pusher-v5/size1000000_std0.01_prand0.0_return-27.1.pth"
    num_steps: 500000
    rollout_length: 3000

# Named experiments that can be used across environments
experiments:
  normal_env:
    description: "Uses default environment xml"
