defaults:
  seed: 0
  eval_interval: 50000
  num_eval_episodes: 5
  use_reward_model: False

  learning_rate: 0.0003 # lr_actor and lr_critic
  hidden_sizes: [256, 256] # units_actor and units_critic
  clip_ratio: 0.2
  gamma: 0.995 # discount factor
  gae_lambda: 0.97
  batch_size: 128
  epoch_ppo: 50
  coef_ent: 0.0
  max_grad_norm: 10.0
  mix_buffer: 1
  cuda: true

# Environment-specific defaults
environments:
  Hopper-v5:
    xml_file: "./xml/Hopper-v5/hopper.xml"
    buffer: "./buffers/Hopper-v5/size1000000_std0.01_prand0.0_return3458.9.pth"
    num_steps: 10000000
    rollout_length: 2048
    hidden_sizes: [64, 64]
    gamma: 0.999
    epoch_ppo: 50
    gae_lambda: 0.99
    coef_ent: 0.0023
    max_grad_norm: 0.7

  HalfCheetah-v5:
    xml_file: "./xml/HalfCheetah-v5/halfcheetah.xml"
    buffer: "./buffers/HalfCheetah-v5/size1000000_std0.01_prand0.0_return11248.4.pth"
    num_steps: 10000000
    rollout_length: 50000
    hidden_sizes: [256, 256]
    batch_size: 256
    learning_rate: 0.001
    gamma: 0.98

  InvertedPendulum-v5:
    xml_file: "./xml/InvertedPendulum-v5/invpend.xml"
    buffer: "./buffers/InvertedPendulum-v5/size1000000_std0.01_prand0.0_return1000.0.pth"
    num_steps: 2500000
    eval_interval: 10000
    rollout_length: 2000
    hidden_sizes: [64, 64]

  Ant-v5:
    xml_file: "./xml/Ant-v5/ant.xml"
    buffer: "./buffers/Ant-v5/size1000000_std0.01_prand0.0_return3075.9.pth"
    num_steps: 10000000
    rollout_length: 50000
    hidden_sizes: [256, 256]

  Pusher-v5:
    xml_file: "./xml/Pusher-v5/pusher.xml"
    buffer: "./buffers/Pusher-v5/size1000000_std0.01_prand0.0_return-27.1.pth"
    num_steps: 10000000
    rollout_length: 30000
    hidden_sizes: [64, 64]

# Named experiments that can be used across environments
experiments:
  normal_env:
    description: "Uses default environment xml"

  modified_reward_hopper:
    use_reward_model: True
    reward_model_path: "./logs/Hopper-v5/airl/normal_env-seed0-20250412-1700/model/step10000000/disc.pth"

  increased_gravity_hopper:
    xml_file: "./xml/Hopper-v5/increased_gravity.xml"

  increased_joint_damping_inverted_pendulum:
    xml_file: "./xml/InvertedPendulum-v5/increased_joint_damping.xml"
